### PR TITLE
Bugfixes for ResilientSession retry logic

### PR DESCRIPTION
**Pull request by asqui**
* max_reties should mean retries, not attempts
* If all attempts fail, re-raise the last exception (instead of
    returning None!?)
* Don't call raise_on_error()  with an Exception, it needs a response!

### CODE REVIEW

**Comment by dbaxa** [comment]
@asqui hopefully we can drop most of the `ResilientSession` logic soon.

**Comment by asqui** [comment]
@dbaxa Oh? In favour of what?

**Comment by dbaxa** [comment]
@asqui hopefully not needing to use it (when JIRA is changed to do the right thing TM).

**Comment by dbaxa** [comment]
@asqui it looks like the latest build for this pull request failed.

**Pull request merged**
