### PR TITLE
fix python 2.7 unicode decode error when jira returns unicode chars

### PR DESCRIPTION
**Pull request by nikepan**

### CODE REVIEW

**Comment by dbaxa** [comment]
@ssbarnea can we merge this?

**Comment by dbaxa** [comment]
A test demonstrating the fix would be nice.

**Comment by nikepan** [comment]
Test case - JIRA with russian error messages. This module used in other files (for example client.py). Only in this file python try concatenate unicode and not unicode strings if error from JIRA is unicode. Problem actual only for python 2

**Comment by ssbarnea** [comment]
Closing because it needs full rebase in order be make it mergeable.

**Pull request closed without merging**
