### PR TITLE
Remove email_user

### PR DESCRIPTION
**Pull request by hdost**
Per the proposal: #565

### CODE REVIEW

**Comment by hdost** [comment]
This seems to have made the difference, I'm not sure if we want to move to a 2.0, though with #397 we will likely need to anyhow.
```
commit 389ec969cf5324175d1773dc464ec33645d096eb               
Author: David Black <dblack@atlassian.com>                    
Date:   Thu Mar 1 14:30:59 2018 +1100                         

    Remove support for renaming users in Jira versions less than 6.0.0.                                                      
                               
    Sem-Ver: api-break         
                               
    Signed-off-by: David Black <dblack@atlassian.com>
```

**Comment by dbaxa** [comment]
@hdost we can always revert that commit if we don't want to release a 2.0.0 version just yet.

**Comment by hdost** [comment]
I think we would have to cherry pick the other commits since I believe it
relies on git history. Not sure how advanced it is.

________________________________________

Harold Dost | @hdost

**Comment by asqui** [comment]
Is this PR currently waiting on the next major release to get merged?

**Comment by ssbarnea** [comment]
Indeed the history prevent a merge so we would have to cherry pick already merged changes and close it after. 

You have me ok to do the work on that as my current load is high. Shortly develop is here only until we merge all useful changes from it to master. Please avoid opening new PR to it.

**Comment by hdost** [comment]
Ok so I did, some parlor tricks and then rebased off of master and it looks like the only thing not already merged was another SemVer breaking change...

**Pull request merged**
