### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by EdgeSync**
Change made to solve warning in JIRA when adding an attachment.

Error:
`2021-03-10 17:18:20,564+0000 https-jsse-nio-8443-exec-98 WARN ***REDACTED*** 1038x776292x1 1pqrv0m 16.85.88.14 /rest/api/2/issue/GIA-3259/attachments [c.a.p.r.c.security.jersey.XsrfResourceFilter] Use of the 'nocheck' value for X-Atlassian-Token has been deprecated since rest 3.0.0. Please use a value of 'no-check' instead.`

Solution:
Edit client.py and change both instances of nocheck to no-check

### CODE REVIEW

**Comment by studioj** [comment]
> Chance made to solve warning in JIRA when adding an attachment.
> 
> Error:
> `2021-03-10 17:18:20,564+0000 https-jsse-nio-8443-exec-98 WARN ***REDACTED*** 1038x776292x1 1pqrv0m 16.85.88.14 /rest/api/2/issue/GIA-3259/attachments [c.a.p.r.c.security.jersey.XsrfResourceFilter] Use of the 'nocheck' value for X-Atlassian-Token has been deprecated since rest 3.0.0. Please use a value of 'no-check' instead.`
> 
> Solution:
> Edit client.py and chance both instances of nocheck to no-check


looks like the maintainers want to have the ci system back up and running before agreeing to any new merges.

if you want to contribute to get yr pr through have a look here => https://github.com/pycontribs/jira/issues/896

**Comment by studioj** [comment]
@EdgeSync  please make sure latest master changes are in your branch so the CI system can run again.
the change seems to be a valid one

**Comment by EdgeSync** [comment]
> @EdgeSync please make sure latest master changes are in your branch so the CI system can run again.
> the change seems to be a valid one

hey @studioj  - i've done a fetch upstream, and merged on my fork. Hope that's what you mean.

**Review by studioj — APPROVED** [review]

**Comment by studioj** [comment]
@ssbarnea seems like a valid change ready to merge

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
