### PR TITLE
Change default template

### PR DESCRIPTION
**Pull request by ReedOnly**
Original template for create new project is removed from Jira and not working anymore

### CODE REVIEW

**Comment by hdost** [comment]
As of which version is this true?

**Comment by ReedOnly** [comment]
For current Jira Cloud, `1001.0.0-SNAPSHOT#100085`.

**Comment by hdost** [comment]
Ideally we want to support backwards compatiblility given that this API is
used with more than just a the cloud offering.

________________________________________

Harold Dost | @hdost

**Comment by ssbarnea** [comment]
I am closing this PR as rejected because is not complete.

1. our testing is passing in JIRA Cloud, so the template was removed on *your* instance, not in general
2. proposed template is agile specific and 100% sure it will break on jira classic
3. there is no test assigned
4. i would have preferred a better logic for detecting the default template instead of using a hardcoded value

Please don't be upset about having this rejected, is just that we want to avoid breaking the library for other hundreds of users. Feed free to make another one that is a bit safer.

**Pull request closed without merging**
