### PR TITLE
Export resource_class_map and fix bug in Role.add_user()

### PR DESCRIPTION
**Pull request by wlupton**
The reason for exporting `resource_class_map` is to allow an external module to support additional resource types without the need to edit resources.py (I had edited it previously but this became a maintenance nightmare).

The `Role.add_user()` bug is (I hope) an obvious one: the `groups` argument was ignored.

---

Some of my local extensions conflict with more recent extensions in `master`. For example, I supported notification schemes and permission schemes, but I took a different approach: I also added new resource types, and the methods return resources rather than dictionaries. For example:

Master:

```python
    @lru_cache(maxsize=None)
    def notificationschemes(self):
        # TODO(ssbarnea): implement pagination support
        url = self._options["server"] + "/rest/api/3/notificationscheme"

        r = self._session.get(url)
        data = json_loads(r)
        return data["values"]
```

Mine:

```python
    def notificationschemes(self) -> List[NotificationScheme]:
        """Get a list of notificationscheme Resources."""
        r_json = self._get_json('notificationscheme')
        notificationschemes = [
            NotificationScheme(self._options, self._session, raw_res_json) for
            raw_res_json in r_json['values']]
        return notificationschemes
```

There was already some level of `Role` support, and I took this approach to extending the interface (this is in a wrapper class that calls methods from the existing master class when it can):

```python
    @translate_resource_args
    def project_roles(self, project: IDorName, *, as_list: bool = False,
                      as_resources: bool = False):
        assert self._mode == 'online'
        # this returns a Dict[str, Dict[str, Any]]
        roles = self._jira.project_roles(project)
        # add a 'name' key (needed if will return a list)
        roles = {name: {**value, 'name': name} for name, value in
                 roles.items()}
        # if requested, convert to Dict[str, ProjectRole]
        if as_resources:
            roles = {name: ProjectRole(self._options, self._session, value) for
                     name, value in roles.items()}
        # if requested, convert to List[]
        if as_list:
            roles = list(roles.values())
        return roles
```

Please let me know if you'd like me to contribute any of these extensions.

### CODE REVIEW

**Comment by studioj** [comment]
looks like the maintainers want to have the ci system back up and running before agreeing to any new merges.

if you want to contribute to get yr pr through have a look here => https://github.com/pycontribs/jira/issues/896

**Comment by ssbarnea** [comment]
@wlupton Closing due to of updates. If you can rebase it tell us to reopen it.

**Comment by helpatbbf** [comment]
That's fine @ssbarnea, but is the reason for closure because it needs rebasing (easy to fix) or the reason given earlier about getting the ci system back up?

**Comment by ssbarnea** [comment]
CI was fixed, I closed as it needed rebase. If you find it useful just make another PR. Only the original OP can update it so that is why I closed it.

**Comment by helpatbbf** [comment]
Great (sorry, I didn't realize). I've rebased and pushed. Thanks.

**Comment by helpatbbf** [comment]
@ssbarnea, I don't see an option to re-open it. Are you able to do this? If not, I can easily create a new PR.

**Comment by ssbarnea** [comment]
Create new one, I am unable to press the button either, not sure why.

**Comment by ssbarnea** [comment]
nope

**Pull request closed without merging**
