### PR TITLE
travis: remove test pypi server

### PR DESCRIPTION
**Pull request by ssbarnea**
Signed-off-by: Sorin Sbarnea <sorin.sbarnea@gmail.com>

### CODE REVIEW

**Comment by asqui** [comment]
Holy crap, the master build is green!

Great work @ssbarnea!!!  🥇:clap:

**Comment by hdost** [comment]
For real, that's great!

**Comment by ssbarnea** [comment]
The big challenge is to make all these PRs green too! 

-- sorin

**Comment by asqui** [comment]
I guess we should rebase all open PRs from the newly green master?

Seems like the sort of thing we should be able to do from the GitHub UI but the only option I can see is "Rebase and Merge", which is not what we want...

Alternatively (and more generally useful, especially for long-lived PRs) would be an option to have Travis run a build on the result of merging the PR branch to master. Do you know if this is possible?

I would then expect this build to be green for any PR branches that have no merge conflicts and don't introduce any regressions...

**Pull request merged**
