### PR TITLE
chore: isort imports

### PR DESCRIPTION
**Pull request by adehad**

### CODE REVIEW

**Comment by studioj** [comment]
looks good => only issue for new devs is => how to add the pre-commit hook
maybe add a description in the readme to help (me) doing that ;-)

**Review by studioj — CHANGES_REQUESTED** [review]
an addition to the readme for precommit would be a useful addition

**Comment by adehad** [comment]
> an addition to the readme for precommit would be a useful addition

I think this is covered by running `tox -e lint`?

**Comment by studioj** [comment]
Ah I thought it was maybe something like this. 

https://pre-commit.com

**Review by studioj — APPROVED** [review]

**Comment by adehad** [comment]
> Ah I thought it was maybe something like this. 
> 
> https://pre-commit.com

It is the same actually. I haven't used it much before but my understanding is that you can use it manually like we have here or automatically per commit as a "pre commit hook" . It is probably more accessible to the community with the current setup to run it manually, but maybe I'm wrong hahah

**Review by dbaxa — APPROVED** [review]

**Comment by studioj** [comment]
@ssbarnea can be merged

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
