### PR TITLE
v1.0.7

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by asqui** [comment]
The Travis "pr" build ([#492.3](https://travis-ci.org/pycontribs/jira/jobs/175195611)) failed on `tests/tests.py::UserAdministrationTests::test_remove_user_from_group` with:
`JiraError HTTP 500 url: https://pycontribs.atlassian.net/rest/api/latest/group`
But only on Python 3.3

Seemed like a transient Jira issue so I re-ran it. Now the build is green, but the logs indicate that test still failed in the same way:

`=== 1 failed, 111 passed, 7 skipped, 2 xfailed, 9 xpassed in 160.56 seconds ====`

@ssbarnea: Any idea what is going on here?

(Also, what is the difference between the Travis 'pr' and 'push' builds? I'm a Travis noob...)

**Comment by asqui** [comment]
PS: Was that merge automatic, upon Travis tests passing, or manual?

**Comment by ssbarnea** [comment]
@asqui It was not automatic but I do plan to automate most of the release process. I am still learning about advanced Travis workflows so we will find out soon.

In the future a successful pull from develop to master should build, test, publish package, publish doc, tag the release, and increase the version number.

This means that when we see a good version on develop we should be able to release it just by doing a single pull request on github, nothing more. There is still work to be done to reach this desired stage.

For the moment I am trying to find a way to rebuild existing PRs. If they can be merged without breaking anything I will accept them or I will close them. I don't want to see any open PRs unless they are marked as [WIP].

**Comment by ssbarnea** [comment]
@asqui do you have a strong use-case for support Python 3.3? As you observed we officially support only `2.7`, `3.4` and `3.5`. I was really close on dropping even the 3.4 but decided to wait a little bit as some wild current distros may still use it.

**Comment by asqui** [comment]
Sorry, that was a typo. I meant Python 3.5. (It's the XXX.3 build in Travis).

Specifically, why is [this build](https://travis-ci.org/pycontribs/jira/jobs/175195611) green, given that the log indicates there was a test failure?

**Pull request merged**
