### PR TITLE
doc/examples: fix jql example which had wrong syntax.

### PR DESCRIPTION
**Pull request by AnneTheAgile**

### CODE REVIEW

**Comment by AnneTheAgile** [comment]
Hmm. re travis fail.

**Comment by asqui** [comment]
I don't understand. What was wrong with the syntax? Your pull request changes it to output the issue key and summary (which now disagrees with the comment on the line above) but seems to use the same syntax.

What am I missing?

**Comment by hdost** [comment]
The actual issue with the syntax is `print` vs `print()` it's not actually an issue with the list comprehension. Python2.7 uses `print` no paren Python3.x uses `print()`

Could add the parentheses, for the example and then make a note saying to remove parentheses if using 2.7.

**Comment by hdost** [comment]
I don't know that I would have merged that.  `print()` only works if you import futures

**Comment by asqui** [comment]
Hmmm, okay, how about this:
```
    # Summaries of my last 3 reported issues
    for issue in jira.search_issues('reporter = currentUser() order by created desc', maxResults=3):
        print('{issue.key}: {issue.fields.summary}'.format(issue=issue))
```

This should be 2/3 compatible, no?

**Pull request merged**
