### PR TITLE
Fix AttributeError issue #298

### PR DESCRIPTION
**Pull request by lukas-bednar**

### CODE REVIEW

**Comment by asqui** [comment]
Actually I'd question what the value of the logging argument is, and whether we should remove that instead of working around it.

Looks like this argument was added to `__init__` in commit ef82109 which is described as "v0.31 manual merge with github fork (used to revive unittests)" and it, to this day, is only used to guard one single log line within `create_project()` so this smells like some debugging code that was accidentally left in and should be removed.

@ssbarnea : Any objection if we solve this issue by removing the `logging` argument to `JIRA.__init__()`

**Comment by lukas-bednar** [comment]
> Actually I'd question what the value of the logging argument is, and whether we should remove that instead of working around it.

It is boolean

**Comment by asqui** [comment]
By "what's the value" I meant "what is the point of having it" not what type of object is assigned to the variable :-)

**Comment by vkrizan** [comment]
I've created a separate pull request #308 to fix logger issues (that I've observed), and to deprecate `JIRA.logging` boolean.

**Comment by ssbarnea** [comment]
I am closing this in favour of PR#308

**Pull request closed without merging**
