### PR TITLE
debug: run a verbose test pypi release to see the errors

### PR DESCRIPTION
**Pull request by studioj**
no idea on how to debug this without creds
running verbose to see the error, im quite sure GHA will keep the pw's hidden in the logs but i dont see any other way than debugging through CI

https://github.com/pycontribs/jira/actions/runs/11983022866/job/33412046787#step:7:700

### CODE REVIEW

**Review by adehad — APPROVED** [review]
@studioj let me know if you are able to merge with your new elevated permissions

**Comment by adehad** [comment]
@studioj you may also want to fix the kebab case in the normal pypi upload

**Comment by studioj** [comment]
> @studioj you may also want to fix the kebab case in the normal pypi upload

ok no idea where you saw this :-s

**Comment by adehad** [comment]
Next time I'm at my machine I can try elevate you to admin to be able to 'merge as admin'

**Pull request merged**
