### PR TITLE
Added Project Category resource type

### PR DESCRIPTION
**Pull request by DerekFields**

### CODE REVIEW

**Comment by ssbarnea** [comment]
Please fix the linting errors if you want to merge this, you can test on your own machine using tox.

**Comment by DerekFields** [comment]
I looked at the file and can't find the error that it is complaining about.
The only lint errors that I see are in the original code that I forked, not
in the changes that I made. I am new to contributing, so I may have missed
something.



Derek Fields
<https://www.linkedin.com/pub/derek-fields/3/186/5a4>

**Comment by laramies** [comment]
Hi, I was wondering if this fix will provide me with the project category.  Currently I have the  issues.fields.project.projectCategory, but is throwing an error in some cases and None in others, but  my issues belongs to projects with Categories defined.   Thanks in advance.

**Comment by ssbarnea** [comment]
Closed as it is outdated, please reopen if needed after rebasing and assuring tests are passing.

**Pull request closed without merging**
