### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by chenchusheng**
expand =“names"，return

### CODE REVIEW

**Comment by chenchusheng** [comment]
expand =“names"，return

**Review by studioj — COMMENTED** [review]
- please use tox to check your code before pushing => currently the black check fails
- as a QA person i would really like to see a test added to check for that specific functionality so it wont break in the future

**Comment by studioj** [comment]
@chenchusheng?

**Comment by studioj** [comment]
no response after +1 yr after requesting changes => close

**Pull request closed without merging**
