### PR TITLE
fix pickling and hashability

### LINKED ISSUE #790: JIRA response still not picklable
**Describe the bug**
Using `pickle.dump` followed by `pickle.load` causes a `RecursionError` to be thrown, even on the `master` development branch.

**To Reproduce**
```
jira_instance = jira.JIRA(jira_link, basic_auth=auth_tuple)
tickets = jira_instance.search_issues('updated >= -1d')
with open('test-jira-pickle.pckl', 'wb') as f:
    pickle.dump(tickets,f)
with open('test-jira-pickle.pckl', 'rb') as f:
    pickle.load(f)  # recursion
```

This seems to be because 1. `self[item]` is used in `resources.py` Resource object 2. `hasattr` is used inside `__getattr__` which is the function that python calls when `hasattr` is used.

**Expected behavior**
JIRA response gets pickled properly and loads properly.

**Stack Trace**
```
File "c:\python37\lib\site-packages\jira\resources.py", line 188 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
  File "c:\python37\lib\site-packages\jira\resources.py", line 202 in __getattr__
...
```

**Version Information**
Python Interpreter: 3.7.0
jira-python: 2.0.1.0rc3.dev2
OS: Windows Server 2016
IPython (Optional): N/A
Other Dependencies:

**Additional context**
N/A

### LINKED ISSUE #842: Issue instance is not hashable
Description: Issue instance is not hashable

Python Interpreter: 3.5.6
jira-python: 2.0.0
OS: Debian GNU/Linux 9.9 (stretch)

Steps To Reproduce:
    1. jira_server = JIRA(server = "...", basic_auth = ("...", "..."))
    2. issue = jira_server.issue("REL-111")
    3. hash(issue)

Stack Trace:
    TypeError: unhashable type: 'Issue'

So, the __hash__ method is missing from Issue class.

### PR DESCRIPTION
**Pull request by adehad**
## Summary of Changes
1. Add default hash and equality functions to the Resource base class, so all inherited members benefit from hashability
2. Fixed pickle work around to a more robust (and now tested) solution

resolves #842 
resolves #790 

Possibly obsoletes #863

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Review by ssbarnea — APPROVED** [review]

**Comment by justinfx** [comment]
Is this known to fix pickling in all cases? I have been dealing with the same recursion bug in python 3.9 / jira 3.5.2 with just this simple line:

```
pickle.loads(pickle.dumps(issue))
```

**Comment by adehad** [comment]
I cannot comment on all cases, but as you can see from the tests added in this PR itself, we have done our best effort by adding to our test suite the equivalent of your suggestion. 
https://github.com/pycontribs/jira/blob/c323c7cc14b42c03d10f7fb315f293878b93021c/tests/tests.py#L71-L78

Our test suite also runs on Python 3.9
https://github.com/pycontribs/jira/blob/c323c7cc14b42c03d10f7fb315f293878b93021c/.github/workflows/jira_server_ci.yml#L14

If you do have an issue, it might be best to raise a new issue with more detail so we can try and reproduce if possible

**Comment by justinfx** [comment]
@adehad I dug into my reproduction code again and found that it was actually caused by some intermediate wrapper code on my side. Sorry for the noise! It does pickle properly now.

**Comment by adehad** [comment]
Great to hear @justinfx

**Pull request merged**
