### PR TITLE
Kerberos mutual authentication in jirashell

### PR DESCRIPTION
**Pull request by pbabinca**
This builds up on #395 and makes #472 available in jirashell.

### CODE REVIEW

**Comment by pbabinca** [comment]
I guess it is good idea to close #395 and merge just this one. I'm used to Gerrit and open separate PR/MR for each commit.

**Comment by ashcrow** [comment]
Build failure here should be fixed by rebasing. Looks like bfac4a89 specifically fixes the missing ChangeLog file.

**Comment by ashcrow** [comment]
Note that even with the rebase the tests look they will fail based on the 404's seen in other PRs coming back from the test server as well as notes about tests failing.

**Comment by ashcrow** [comment]
👍

**Comment by ashcrow** [comment]
@ssbarnea PTAL when you have a few.

**Comment by csasalu** [comment]
@ssbarnea please merge this request if it looks good.

**Comment by ssbarnea** [comment]
Please reopen a new PR after rebasing your fork so it would create a correct PRs that does not touch unrelated files.

**Comment by tuukkamustonen** [comment]
@ssbarnea Please check #589 and #590.

**Pull request closed without merging**
