### PR TITLE
Add support for some Service Desk API calls

### PR DESCRIPTION
**Pull request by dbravender**
This adds support for some of the API calls in the new JIRA Service Desk API: https://docs.atlassian.com/jira-servicedesk/REST/cloud/#servicedeskapi/

### CODE REVIEW

**Comment by dbravender** [comment]
@ssbarnea thank you for the information. I will add tests and resubmit the PR.

**Comment by ssbarnea** [comment]
Let me know when you finished the detection of jira service desk so I can ask Atlassian to enable service desk for our testing instance. I don't want to ask them this before having the test so we do know that detection works.

**Comment by dbravender** [comment]
@ssbarnea I added `supports_service_desk` that returns `True` when Service Desk is enabled on an instance:

```python
>>> client = JIRA(server='https://issues.apache.org/jira')
>>> client.supports_service_desk()
False
>>> client = JIRA(server='https://pycontribs.atlassian.net')
>>> client.supports_service_desk()
True
```

I'll add more tests in the next few days.

**Comment by igor-pavlenko** [comment]
@dbravender Hi, I see you are working on integration with Jira Service Desk. I saw you pull request, but it was before you started to add more feautres/tests.
I also started to work:
https://github.com/igor-pavlenko/jira

I think we can do it together. What do you think? And how we can merge our branches and divide API methods between us?

Thanks.

**Comment by ssbarnea** [comment]
So far I like the changes and I see that it does pass the tests. Let me know if is ready to be merged.

**Comment by dbravender** [comment]
> Let me know if is ready to be merged.

We have been using this on production for almost a month without issues. I think this can be merged.

**Comment by dbravender** [comment]
> I think we can do it together. What do you think? And how we can merge our branches and divide API methods between us?

@igor-pavlenko I just saw this comment. I have implemented all of the functionality we will need to use from Service Desk for now but I do see that you implemented more calls and did some things in a cleaner way than I did - like paginating the Service Desk listings. I think we can definitely merge our work an make something better.

**Comment by igor-pavlenko** [comment]
@ssbarnea @dbravender Would you be so kind to give me a tip, how it better to do? 
1) I should for @dbravender branch & merge my methods to it
or
2) I should wait until @ssbarnea merge this branch to dev and than I will add my methods & create new pool request?

Thanks!

**Pull request merged**
