### PR TITLE
Revert "build:chore"

### PR DESCRIPTION
**Pull request by hdost**
This reverts commit a9388536180789e3473a7804ed5743acd1dd38e7.

### CODE REVIEW

**Comment by ssbarnea** [comment]
@hdost please don't merge new change to master until I fix travis code. There are lots of workaround settings that were needed for testing travis and the only way to test them was to push to master and to add the tags. 

I will try to fix it today so we can continue merging "real changes".

**Comment by ssbarnea** [comment]
I am aware master build is broken but I will fix it today, dont merge anything yet.

**Comment by hdost** [comment]
Sounds good.

________________________________________

*Harold Dost* | @hdost

**Comment by ssbarnea** [comment]
There were multiple issues related to Travis and I didn't want to add an endless list of commits as "attempt to fix travis". I already managed to fix the pypi release code but now i need to update github release which no longer works after I switched from travis.org to travis.com.

**Comment by hdost** [comment]
@ssbarnea I would say double check the API key you have in the Travis file
has the appropriate permissions.

________________________________________

Harold Dost | @hdost

**Comment by ssbarnea** [comment]
Apparently I was able to fix it, it did publish to pypi and github releases version 2.0.0rc10.

**Comment by hdost** [comment]
Excellent!

________________________________________

*Harold Dost* | @hdost

**Pull request closed without merging**
