### PR TITLE
make_tests_runnable_on_Jira_VM

### PR DESCRIPTION
**Pull request by Achimh3011**
PR brought up to current state. Already includes PR #149, you might want to merge that one first, it is quite straight forward.

This runs all local tests without error. On Travis it at least tries all tests, what is more than master currently does.

### CODE REVIEW

**Comment by Achimh3011** [comment]
BUMP

**Comment by Achimh3011** [comment]
BUMP^2

**Comment by ssbarnea** [comment]
In order to easy the work on the library I sent you an invite to the group, so you will be able to make changes directly and ot accept the pull requests. Thank you!

**Comment by Achimh3011** [comment]
Thx, joined.

**Pull request merged**
