### PR TITLE
Update client.py

### PR DESCRIPTION
**Pull request by fabio-silva-movile**
Adding support to performe transitions using it name, as requested by issue #8. Not tested yet, just a draft.

### CODE REVIEW

**Comment by sargentstudley** [comment]
@fabio-silva-movile, would you like some unit tests written for this?

**Comment by fabio-silva-movile** [comment]
@sargentstudley yes, it's a good idea make unit tests, but what jira instance can we use to test this? Or you are think in some mock strategy to perform this? Maybe @ssbarnea can help us on this.

**Comment by ssbarnea** [comment]
I will reject this merge request because the API change of the function. Please rename the transactionId parameter to transaction and use python to decide if is a number of a string. We do not need two parameters. Also please be sure that you are doing a case insensitive match, if I call it with "open" it should perform "Open". Is important to keep our APis friendly :)

If you contact me by chat (skype / google chat / imessage), I will create accounts for you on the test server, so you can run the unitests locally.

**Comment by fabio-silva-movile** [comment]
Ok, good points @ssbarnea , I wil review this and make the necessary changes and tests.

**Comment by ssbarnea** [comment]
Please register yourself to https://pycontribs.atlassian.net/admin/signup and I will give admin permissions to your account so you can perform the tests.

**Comment by fabio-silva-movile** [comment]
Ok, I have registered with username fabioos

**Comment by ssbarnea** [comment]
@fabio-silva-movile you have admin rights, now and you should be able to run the unit tests.
```
export CI_JIRA_URL=https://pycontribs.atlassian.net
export CI_JIRA_ADMIN=your_admin
export CI_JIRA_ADMIN_PASSWORD=
export CI_JIRA_USER=your_simple_login
export CI_JIRA_USER_PASSWORD=
```
You will have to create a new account for limited user. After this, only `python setup.py test`

**Pull request closed without merging**
