### PR TITLE
Make tests runnable on local jira vm

### PR DESCRIPTION
**Pull request by Achimh3011**
As the Travis build is broken and I do not have much idea what I could do about it, I tried to run the tests locally, against a Jira 7.0 VM from Atlassian. 

Turned out that a lot of tests rely on specifics of the Jira installation, so I conditionally skip a lot of tests if run locally. The ones that don't rely on specifics now work, including PEP8-Checks and sphinx warnings, across all python versions listed in ``tox.ini``. Just run ``./tests.local --tox``.

### CODE REVIEW

**Comment by Achimh3011** [comment]
BUMP

**Comment by ssbarnea** [comment]
Please try to resolve it first, I will accept it, good changes. Let's hope it will not take ages to repair the integration tests on Travis.

**Comment by Achimh3011** [comment]
So that means that you are not going to merge PRs until Travis is fixed? I'll look into it, but as previously written, I have no experience with it (nor with the specific setup for this project, which looks .. special).

**Comment by ak-ambi** [comment]
I don't understand why this PR was not merged. You cannot fix Travis without fixing all tests, and some of these fixes may be needed to successfully execute tests on any environment. And that would be great if we could run tests locally before creating new PR.

**Comment by Achimh3011** [comment]
I'm currently rebasing the PR to yesterday's HEAD, unfortunately a number of things broke and I'm still understanding why and where. It's the old story of having a hard time getting back to a green CI once that was lost and development continues on a red CI.

**Pull request closed without merging**
