### PR TITLE
Fixed Citrix Logo image URL

### PR DESCRIPTION
**Pull request by sevenfourk**
Hey guys, I'm not sure which logo was before, but this should be working. The only thing bothers me it's huge.

### CODE REVIEW

**Comment by sevenfourk** [comment]
Not sure that error refers to my changes:
https://travis-ci.org/pycontribs/jira/jobs/176038649#L457

**Comment by asqui** [comment]
The Python 3.5 build on Travis seems to be unstable. I re-ran it and it's passed now.

**Comment by asqui** [comment]
PS: The image sizes thing is a GitHub limitation; unfortunately they seem to ignore image sizing markup in reStructuredText for some reason. :-(

**Comment by sevenfourk** [comment]
@asqui, thanks.

**Pull request merged**
