### PR TITLE
Added an explicit dependency to oauthlib in order to avoid depending on the outdated pycrypto library

### PR DESCRIPTION
**Pull request by Rovanion**
See:  https://github.com/pycontribs/jira/issues/619

### CODE REVIEW

**Comment by Rovanion** [comment]
Seems to me like the build failures are unrelated to the proposed changes.

**Comment by asqui** [comment]
Looks like @ssbarnea might have done a force push to master? I can't work out how else that first commit appeared on your branch.

In any case, if you remove that first commit from your branch (a938853) it should be good to merge.

**Comment by ssbarnea** [comment]
Wait for me to fix the travis release and once I am done a simple rebase would work.

**Comment by ssbarnea** [comment]
Fix already merged, this is nolonger needed. Lets hope this change would not upset other consumers.

**Pull request closed without merging**
