### PR TITLE
Kerberos auth in jirashell

### PR DESCRIPTION
**Pull request by tuukkamustonen**
Cherry-picked from #473 (by @pbabinca) to make jirashell support kerberos auth.

(the original PR is closed for being out-of-date and the author seems somewhat inactive.)

### CODE REVIEW

**Comment by pbabinca** [comment]
@tuukkamustonen thanks for both PRs!

**Comment by ssbarnea** [comment]
I am finally facing the kerberos joy myself, for the moment struggleing to make it work in JIRA() class. Apparently it does not work right out of the box.

**Comment by tuukkamustonen** [comment]
@ssbarnea `JIRA(..., kerberos=True)` iirc (and ensure you have `requests-kerberos` package installed).

**Comment by tuukkamustonen** [comment]
@hdost Done

**Comment by tuukkamustonen** [comment]
@hdost @ssbarnea What do you think, could we go merge this?

**Pull request merged**
