### PR TITLE
fix bug with accountId is not passed

### PR DESCRIPTION
**Pull request by nakonovalov**
fix "The 'accountId' query parameter needs to be provided"

### CODE REVIEW

**Comment by adehad** [comment]
Unfortunately at the moment this will fail for Jira Server/Data Center, I'll approve the CI run but most likely it will fail.

This is on our radar though, just need to find the best way to go about supporting both Jira Cloud and Jira Server/Data Center.

**Comment by adehad** [comment]
@nakonovalov I've made a separate branch (refer #1109) that I think addresses this, would be great to get confirmation from you that it works for you too.

**Comment by nakonovalov** [comment]
Thank you!

**Comment by studioj** [comment]
> Thank you!

does that mean you checked on your side that it works?

**Comment by adehad** [comment]
Closing in favour of #1109

**Pull request closed without merging**
